### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by franktbc** [Azure/active-directory-dotnet-graphapi-b2bportal-web#21]
Followed setup 
On signing for configuration of web site:

Error
An error occurred while processing your request.

/Home/Error?message=unsupported_response_type

**Comment by franktbc** [comment]
ok after ticking all the right boxes... im hybrid... getting a user profile not found from the edit profile.. meaning its not getting the oid. from azure ?

**Comment by craigmpeters** [comment]
> 
> 
> ok after ticking all the right boxes... im hybrid... getting a user profile not found from the edit profile.. meaning its not getting the oid. from azure ?

I had this issue, for the Azure AD Application which requires "Read and write directory data" go to Authentication and tick "ID Tokens" under **Advanced Settings**

**Comment by franktbc** [comment]
all fixed, not sure what i did but it works

**Comment by jamiepetey** [comment]
> ok after ticking all the right boxes... im hybrid... getting a user profile not found from the edit profile.. meaning its not getting the oid. from azure ?
> 
> I had this issue, for the Azure AD Application which requires "Read and write directory data" go to Authentication and tick "ID Tokens" under Advanced Settings

Hi Craig, thanks for sharing this. I had a similar issue and enabling ID Tokens on the "B2B Admin App" resolved this. This leads me to ask if this approach is ideal from a security perspective. Looking into Implicit Flow, I found this - https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-oauth2-implicit-grant-flow 
"If you are planning an SPA architecture, have no backend components or intend to invoke a Web API via JavaScript, use of the implicit flow for token acquisition is recommended."

I don't consider myself a develop so hope someone on this thread can add some insight.
Would you consider the B2B self service app an SPA architecture that fits the specs for implicit flow ?

**Comment by craigmpeters** [comment]
Yes it certainly is not a SPA and it is doing it from the backend rather than something done in the frontend.

**Comment by jamiepetey** [comment]
The literature from the main B2B github project states - "Allows self-service provisioning of guest accounts in a tenant. Portal enables this via API calls to the Microsoft Graph". 

Azure AD Graph API supports XML or Javascript Object Notation (JSON) content types for requests and responses.  
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api#features

With this in mind, could we consider the B2B self service app leverages Web API via JavaScript so it is fit for using implicit flow ID tokens?

**Comment by craigmpeters** [comment]
Well, yeah it does use the Graph API, the difference is that it is not the user making the API call but the backend system making the API call, I do not know enough about the particular oAuth security issue to make a solid comment around this.
