### ISSUE TITLE
ARM Template QueueName Variable

### ISSUE THREAD

**Issue by jg-fisher** [Azure/active-directory-dotnet-graphapi-b2bportal-web#33]
'Q' in the value needs to be lowercase, otherwise validation will fail due to Storage Accounts not permitting capital letters.

"QueueName": "[concat('Queue', uniqueString(resourceGroup().id))]",

**Comment by bretthackermsft** [comment]
Interesting. That's definitely a bug but weird that it's not come up until now. There is a dev branch of this repo that is newer and that bug is corrected there. I'll update master ALTHOUGH as a tool sample, this repo is deprecated in favor of Entitlement Management, per the updated readme.
