### ISSUE TITLE
Unable to deploy the solution to Azure

### ISSUE THREAD

**Issue by tarun00197** [Azure/active-directory-dotnet-graphapi-b2bportal-web#34]
I followed the step by step process in the Setup.md page, But I am unable to deploy the solution to my tenat. I am the global administrator for my tenant

Error:

> Deployment to resource group 'xxxxxxxx' failed.
> Additional details from the underlying API that might be helpful: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.

When I Checked the Resource group deployments 
Error:

> {"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\"\r\n }\r\n}"}]}

**Comment by tarun00197** [comment]
Is there any to deploy the complete solution from the VS instead of deploying to Azure directly from the Github. Can anyone provide me the documents or reference for the same

**Comment by ShahJe** [comment]
Experienced same issue.

**Comment by polchek** [comment]
Having the same issue.

**Comment by ShahJe** [comment]
> Having the same issue.

For me the script created all the resources but did not deploy the site. I cloned the repo and deployed to azure from visual studio. If compiler complains about missing hdsettings.config file then simply delete it and remove its reference from app.config/web.config.

**Comment by polchek** [comment]
> > Having the same issue.
> 
> For me the script created all the resources but did not deploy the site. I cloned the repo and deployed to azure from visual studio. If compiler complains about missing hdsettings.config file then simply delete it and remove its reference from app.config/web.config.

Thanks! I will give it a try

**Comment by wintech147** [comment]
Has anybody been able to get this to deploy using the deploy to azure option? I'm not very good at dev and just need the sample site for a B2B demo. Any help would be greatly appreciated! I see deploying via VS is an option but I'm not sure how to do that :)

**Comment by bretthacker** [comment]
All, this repo is deprecated and not receiving any love going forward. We've left it here as a code sample for working with the self-service Graph API. That said, the dev branch has received more recent love than master, although it is also still pretty old. I just ran the deployment from dev, in South Central, and I was able to deploy successfully using the ARM template.

To deploy dev, please copy the URL from the Deploy to Azure link, and edit the repo name at the end to match dev:

https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Factive-directory-dotnet-graphapi-b2bportal-web%2Fdev%2Fazuredeploy.json

Once you're filling out the form in Azure, be sure to change the repo name at the bottom of the form from master to dev as well. And again...YMMV. 

**As indicated in the readme in the master repo**: If you wish to enable users from other organizations to request access, and upon approval be provisioned with guest accounts and assigned to groups, apps and SharePoint Online sites, then instead use Azure AD entitlement management to configure policies that manage access for external users.
