### ISSUE TITLE
Your app service is up and running.

### ISSUE THREAD

**Issue by Nikosss2010** [Azure/active-directory-dotnet-graphapi-b2bportal-web#41]
Hi,
I deployed the template and everything was ok.
Hovewer, when I follow the wep app link, I have:
Your app service is up and running. (the hostingstart.html page inside root folder)
How can I have the proper B2B page described in the setup?
Thanks for your help.

**Comment by V4LC0** [comment]
Hello,
We're experiencing the same issue. There is only the default page saying:
"Your app service is up and running.
Time to take the next step and deploy your code."
After clicking on Deployment center we're getting a Server Error.

The App is up and running, but the last deployment step regarding sourcecontrol always fails...

Type: Microsoft.Web/sites/sourcecontrols
Error:
{
    "status": "Failed",
    "error": {
        "code": "ResourceDeploymentFailure",
        "message": "The resource operation completed with terminal provisioning state 'Failed'."
    }
}

Thanks for help.

**Comment by bretthackermsft** [comment]
This sample is no longer being actively maintained; we're keeping it published for archive and reference purposes. Please feel free to branch and work out whatever's going on. In this specific case see if you can pull the source down, get it running in VS, and deploy from there. The ARM APIs in this deploy template are a few years old now.

We also strongly suggest you take a look at the self-service B2B invitation capabilities features that are now native to your Azure AD tenants. Most of the capabilities in this sample have been implemented and are available. https://docs.microsoft.com/en-us/azure/active-directory/external-identities/self-service-sign-up-user-flow
