### ISSUE TITLE
Cleanup Section

### ISSUE THREAD

**Issue by anthonyonazure** [Azure/active-directory-dotnet-graphapi-b2bportal-web#5]
It's a minor detail but I have run into it twice.  When you copy the url from the newly created app service, it is an insecure url http not https, and then when you replace the "https://loopback.com" url and use the portal to send an invite, it returns an error 

> the reply address 'http://....' does not match does not match the reply address for configured for the application ...

I went back the app service copied the url again from the overview blade, which didn't fix it, after looking at my clipboard and the url, seeing they were identical, I noticed there was no "s".  Put the s after http in all of the reply addresses and homepage urls and it immediately starts working.  

I thought it was my custom domain in AAD but this happened again to me this week withe a different tenant.

Thanks for the tutorial.

**Comment by bretthacker** [comment]
Thanks! I've added a note to ensure that the HTTPS protocol is used when copying the URL over.
